### PR TITLE
Adding Android support

### PR DESCRIPTION
**Pull request by LikeTheSalad**
Solves #8

### CODE REVIEW

**Comment by xvik** [comment]
Thank you very much! 
I just need one more thing: a sample android project. The main problem is that i'm not developing android apps (and never did) so I need a usage example to add it as a test case (to make sure it works and to catch regressions later). 

It might be a complete android project in examples dir or, at least, please post an example gradle script (as comment here)  and a sample application source (the simplest hello word).

**Comment by xvik** [comment]
By the way, why android lib project support is enough? What if user use android application plugin? (maybe it is always used together with the library plugin)

**Comment by LikeTheSalad** [comment]
Thank you for your feedback! I'll add a sample project for tests 👍 

> By the way, why android lib project support is enough? What if user use android application plugin? (maybe it is always used together with the library plugin)

Tbh it's mostly because I was focusing on the use case of [Android apis availability](https://developer.android.com/studio/write/java8-support-table), for which I have a problem right now because the "[native mechanism](https://developer.android.com/studio/write/java8-support#library-desugaring)" provided for Android libs is [forcing consumer projects](https://github.com/open-telemetry/opentelemetry-android/issues/682) (android apps) to do some setup that's not needed in some cases, so that's why I was focusing on "well-behaved libraries" essentially, given that an android app will always be the last build (no other android project can "consume" an app), people could just use the "native mechanism" for apps without worrying about affecting anybody else. However, I didn't think of other use cases, maybe not necessarily related to Android apis availability, so I think it's fine to also add support for apps, it should be the same process too so I'll just add it to this PR.

**Comment by LikeTheSalad** [comment]
Hi @xvik - I've added support for android apps and also some examples, please have another look when you get a chance!

**Comment by xvik** [comment]
Thank you very much!

**Pull request merged**
