### PR TITLE
Update Gradle to 6.0.1

### PR DESCRIPTION
**Pull request by LordRaydenMK**
- Move the Build Scan plugin to `settings.gradle`
- Bump `ru.vyarus.quality` to fix the build

Note: I was trying to update the Gradle version for arrow-kt but this plugin was failing. Hoping this will fix the issue.

### CODE REVIEW

**Comment by LordRaydenMK** [comment]
Travis failing seems to be related to this: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

from the comments switching to `openjdk8` might fix it. Thoughts?

On the failing tests, not sure what the issue might be, my groovy skills are not enough to fix it.

**Comment by xvik** [comment]
Sorry, I'm releasing dropwizard-guicey right now and can't look this. I'll answer you tomorrow.

**Comment by xvik** [comment]
> from the comments switching to openjdk8 might fix it. Thoughts?

Yes, it would help, I just didn't update project build yet.

I tried to run plugin with gradle 6 and I don't see any problems. What issue are you trying to solve?
arrow-kt is an organization with multiple projects, on which one I could reproduce your issue?

**Comment by LordRaydenMK** [comment]
Arrow was failing when this plug in was applied (using Gradle 6). But looks like the project was using an older version of this plug in (and other outdated plugs in).

So bumping that fixed the issue for Arrow 😁

I am still happy to work on this pr though, since I already started. I am just not sure what the issue with the tests is and I would need help.

We could also close it and revisit in the future if you are busy. 

Thanks for looking into this.

**Comment by xvik** [comment]
> We could also close it and revisit in the future if you are busy.

For now, yes lets put it on hold. There are problems that need investigation. I was planning to update the plugin in any case, but a bit later: plugin should be updated to use animalsniffer directly instead of ant tasks to be able to override asm version (this is important for android, and currently android level checks is almost the only useful plugin usage as java 9+ have built-in api level control)

**Comment by LordRaydenMK** [comment]
I managed to update the gradle version in Arrow independent on this.

Since you are busy at the moment and my Groovy skills are no the best, let's close and revisit in the future.

Thanks for taking the time to comment on the PR.

**Pull request closed without merging**
